# 10.1 MySQLサーバを起動する
# 起動後に下記とか利用して理解を深める
# - docker exec -it db mysql -u root -p
# - docker exec -it db bash
services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"