# MySQL勉強
# 起動後に下記とか利用して理解を深める
# - docker exec -it db mysql -u root -p
# - docker exec -it db bash
services:
  db:
    image: mysql:9.4.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sampledb
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
      - type: bind
        source: ./seeds
        target: /docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db_data: